config/routes.rb
Rails.application.routes.draw do

  get '/restaurants', to: "restaurants#index"
  get '/restaurants/new', to: "restaurants#new", as: :new_restaurant
  post '/restaurants', to: "restaurants#create", as: :create_restaurant
  get '/restaurants/:id', to: "restaurants#show", as: :restaurant

  # get '/restaurants/:restaurant_id/reviews/new', to: "reviews#new", as: :new_restaurant_review
  post '/restaurants/:restaurant_id/reviews', to: "reviews#create", as: :restaurant_reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian], message: '%{value} is not valid' }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, numericality: { only_integer: true, in: 0..5 }
  validates :content, :restaurant_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.category = @restaurant.category&.downcase
    if @restaurant.save
      redirect_to restaurant_path(@restaurant), notice: "Restaurant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

private

  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :phone_number, :address)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>


    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit%>
<% end %>

app/views/restaurants/index.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <h1>All Restaurants</h1>
  <%= link_to "Add a new restaurant", new_restaurant_path, class: "btn btn-light" %>
  </nav>

<div class="container p-3">

  <div class="container">
    <% @restaurants.each do |r| %>
    <h4>Name: <%= link_to r.name, restaurant_path(r) %></h4>
    <p>Location: <%= r.address %></p>
    <% end %>
  </div>

</div>

app/views/restaurants/new.html.erb
<%= render "form", restaurant: @restaurant %>

<%= link_to "Back to all restaurants", restaurants_path %>

app/views/restaurants/show.html.erb
<div class="container p-3">
  <h1><%= @restaurant.name %></h1>
  <div class="container">
    <h6>Location: <%= @restaurant.address %></h6>
    <h6>Type of cuisine: <%= @restaurant.category %></h6>
    <h6>Telephone: <%= number_to_phone(@restaurant.phone_number) %></h6>

<p>Reviews</p>
<% @restaurant.reviews.each do |r| %>
<p><%= r.rating %></p>
<p><%= r.content %></p>
<% end %>

<p>Write a review</p>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

  <%= link_to "Write a review", restaurant_reviews_path(@restaurant), class: "btn btn-secondary"%>
  <%= link_to "Back to all restaurants", restaurants_path, class: "btn btn-info"%>
  </div>
</div>